### ISSUE TITLE
What should be in node /home/twang6/macweb-prod/bundle/main.js?

### ISSUE THREAD

**Issue by ashley-holton** [shrutiravikumar/macweb#40]
In the start.sh file, line 6 references /home/twang6/macweb-prod/bundle/main.js. How do I make my own main.js file and what should be in it? Perhaps add instructions for this in the readme.

**Comment by ed1d1a8d** [comment]
Here is my attempt to remember the build process.
It largely follows the instructions at https://guide.meteor.com/deployment.html#custom-deployment.

1. From the root of this repo, run `npm install`.
2. Run `meteor build --architecture os.linux.x86_64`. This will create a file called `macweb.tar.gz` that is the bundled version of the macweb site.
3. Run `tar xvzf macweb.tar.gz` to unbundle the macweb site. This will create a bundle folder, which contains main.js.
4. Move `bundle` and `start.sh` from repository into a standalone directory out of which the production macweb site will be served (e.g. I used to use `/home/twang6/macweb-prod` as the standalone directory). You will need to modify start.sh to point to your new production directory. Also I used to use nvm to manage nodejs, which is why I need to first load node with the line https://github.com/shrutiravikumar/macweb/blob/c0b626d142c3410871b6ba6dfc5b37b1f11030f1/start.sh#L2. start.sh simply starts up the webserver.
5. Have systemd auto run start.sh. This makes it so the macweb server automatically starts when the computer restarts, and if it ever crashes. See https://linuxconfig.org/how-to-automatically-execute-shell-script-at-startup-boot-on-systemd-linux/ for instructions. You can see `/etc/systemd/system/macweb.service` for the existing systemd script.

**Comment by ashley-holton** [comment]
@ed1d1a8d Thanks for the explanation! And then is this the same process you would run to test the website locally? Or just to deploy? If it's just the deployment process, how would I go about testing the website locally?

**Comment by ashley-holton** [comment]
@ed1d1a8d never mind, I figured out how to test locally with the help of the meteor guide, thanks again!
